# Generated by Django 4.2.26 on 2025-11-12 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Όνομα Κατηγορίας')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή')),
            ],
            options={
                'verbose_name': 'Κατηγορία',
                'verbose_name_plural': 'Κατηγορίες',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('photo', models.ImageField(upload_to='report_photos/', verbose_name='Φωτογραφία')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Γεωγραφικό Πλάτος')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Γεωγραφικό Μήκος')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Διεύθυνση (προαιρετικά)')),
                ('status', models.CharField(choices=[('PENDING', 'Σε εκκρεμότητα'), ('IN_PROGRESS', 'Σε εξέλιξη'), ('RESOLVED', 'Επιλύθηκε')], default='PENDING', max_length=20, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημ/νία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημ/νία Ενημέρωσης')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UrbanMapApp.category', verbose_name='Κατηγορία')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης που έκανε την αναφορά')),
            ],
            options={
                'verbose_name': 'Αναφορά',
                'verbose_name_plural': 'Αναφορές',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='UrbanMapApp.report', verbose_name='Αναφορά')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Ψήφος',
                'verbose_name_plural': 'Ψήφοι',
                'unique_together': {('user', 'report')},
            },
        ),
    ]
